sudo: false
notifications:
  email: false
env:
  global:
    - LUAROCKS_VERSION=2.3.0
    - ARGON2_VERSION=20151206
    - ARGON2_DIR=$HOME/argon2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit-2.0
    - LUA=luajit-2.1
before_install:
  - source .ci/setenv_lua.sh
  - bash .ci/setup_argon2.sh
  - pip install --user cpp-coveralls
  - luarocks install busted
  - luarocks install luacov-coveralls
install:
  - luarocks make argon2-*.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage" ARGON2_INCDIR=$ARGON2_DIR/src ARGON2_LIBDIR=$ARGON2_DIR
  - make clean
script:
  - busted -v -o gtest --repeat 3 --coverage spec
after_success:
  - coveralls --dump c.report.json
  - luacov-coveralls -i argon2 -j c.report.json
cache:
  pip: true
